### Get tooele tech route
GET http://localhost:3000/ttech HTTP/1.1

### get root  path  /

GET http://localhost:3000/ HTTP/1.1

### get all students
GET http://localhost:300/students HTTP/1.1

### get one student
GET http://localhost:3001/students/668d81b5e53e7d3092fc10e1 HTTP/1.1

### create a student
POST http://localhost:3001/students HTTP/1.1
Content-Type: application/json

{
    "firstName": "Phil",
    "lastName": "Reeves",
    "email": "bowser@killer.com",
    "age": 34,
    "currentCollege": "Assassin's Academy"
}

###update student
PUT http://localhost:3001/students/668d81b5e53e7d3092fc10e1 HTTP/1.1
Content-Type: application/json

{
  "firstName": "Petunia",
  "lastName": "Gai",
  "email": "pgait@gmail.com",
  "age": "31",
  "currentCollege": "Utah State"
}
